In [1]:
import numpy as np

In [4]:
my_array = np.arange(10000)

In [5]:
my_array

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [6]:
%time my_array = np.arange(10000)

CPU times: user 26 µs, sys: 19 µs, total: 45 µs
Wall time: 36 µs


In [7]:
data = np.random.randn(2,3)

In [8]:
data

array([[-0.08222933,  1.09319732,  0.07552031],
       [-0.35459071,  0.49347189,  1.82647379]])

In [9]:
data.shape

(2, 3)

In [10]:
data * 10

array([[-0.82229325, 10.9319732 ,  0.75520305],
       [-3.54590711,  4.93471894, 18.26473787]])

In [13]:
data * np.random.randn(2,3)

array([[ 0.04000791, -0.06608629,  0.09196736],
       [ 0.55295886,  0.09692343, -0.02012387]])

In [14]:
arr1 = np.array([1,2,3])

In [15]:
arr1

array([1, 2, 3])

In [16]:
arr1.dtype

dtype('int64')

In [17]:
arr1 = np.array([0.1,2,0.3])

In [18]:
arr1.dtype

dtype('float64')

In [19]:
arr1[0]

0.1

In [20]:
arr1[0] = 10

In [21]:
arr1

array([10. ,  2. ,  0.3])

In [22]:
arr2 = np.array([1,2,3])

In [23]:
arr2[0] = 10.6

In [24]:
arr2

array([10,  2,  3])

In [25]:
arr2.fill(100)

In [26]:
arr2

array([100, 100, 100])

In [27]:
arr1.fill(100)

In [28]:
arr1

array([100., 100., 100.])

In [32]:
my_array = np.arange(36)

In [33]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [40]:
my_array = my_array.reshape(6,6)

In [42]:
my_array[0,3:5]

array([3, 4])

In [52]:
slice_arr1 = my_array[2::2, ::2]

In [51]:
my_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [53]:
slice_arr1

array([[12, 14, 16],
       [24, 26, 28]])

In [54]:
A = [2,1,3,5,4]

In [ ]:
index = np.arange(len(A)) + 1

In [59]:
index

array([1, 2, 3, 4, 5])

In [56]:
bulbs = np.array(A)

In [60]:
bulbs

array([2, 1, 3, 5, 4])

In [70]:
sum(np.cumsum(index) == np.cumsum(bulbs))

3

In [67]:
np.cumsum(index)

array([ 1,  3,  6, 10, 15])

In [68]:
np.cumsum(bulbs)

array([ 2,  3,  6, 11, 15])

In [69]:
np.cumsum(index) == np.cumsum(bulbs)

array([False,  True,  True, False,  True])

In [71]:
array = [1,2,3,-9,5,7,-99,2,8]

In [72]:
np.cumsum(array)

array([  1,   3,   6,  -3,   2,   9, -90, -88, -80])

In [73]:
np.cumsum(array) > 0 

array([ True,  True,  True, False,  True,  True, False, False, False])

In [75]:
from collections import defaultdict

In [76]:
my_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [82]:
resultado = defaultdict(int)
for linha in my_array.flat:
        resultado[elemento] += 1

In [86]:
np.array(my_array.flat)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [89]:
A = np.array(my_array)

In [90]:
A 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [92]:
np.unique(A, return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [93]:
? np.unique

In [94]:
elementos, contadores = np.unique(A, return_counts=True)

In [95]:
elementos

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [96]:
contadores

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [99]:
dict(zip(elementos, contadores))

{0: 1,
 1: 1,
 2: 1,
 3: 1,
 4: 1,
 5: 1,
 6: 1,
 7: 1,
 8: 1,
 9: 1,
 10: 1,
 11: 1,
 12: 1,
 13: 1,
 14: 1,
 15: 1,
 16: 1,
 17: 1,
 18: 1,
 19: 1,
 20: 1,
 21: 1,
 22: 1,
 23: 1,
 24: 1,
 25: 1,
 26: 1,
 27: 1,
 28: 1,
 29: 1,
 30: 1,
 31: 1,
 32: 1,
 33: 1,
 34: 1,
 35: 1}

In [114]:
data = [1,2,3,-9,5,7,-99,2,8]*500

In [117]:
def calcular(data):
    resultados = sum(data)
    for index1, numero in enumerate(data):
        for index2, outros_numeros in enumerate(data):
            if index1 <= index2:
                if resultados < sum(data[index1:index2+1]):
                    resultados = sum(data[index1:index2+1])
    return resultados

In [119]:
%time calcular(data)

CPU times: user 2min 19s, sys: 828 ms, total: 2min 20s
Wall time: 2min 27s


19